/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessproje;

import javax.swing.JOptionPane;

/**
 *
 * @author TozLu
 */
public class giris extends javax.swing.JFrame {

    /**
     * Creates new form giris
     */
    public giris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kullaniciadi = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        saglıkmerkezi = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        kullaniciaditext = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 810));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kullaniciadi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kullaniciadi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        kullaniciadi.setOpaque(false);
        kullaniciadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciadiActionPerformed(evt);
            }
        });
        jPanel1.add(kullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 360, -1));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 360, 20));

        saglıkmerkezi.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        saglıkmerkezi.setForeground(new java.awt.Color(255, 255, 255));
        saglıkmerkezi.setText("Sağlıklı Yaşam Bilgi Sistemi\n");
        jPanel1.add(saglıkmerkezi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 430, 80));

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Şifre:");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 30, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\girisyap.png")); // NOI18N
        jButton1.setText("Giriş Yap!");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 320, 60));

        kullaniciaditext.setForeground(new java.awt.Color(255, 255, 255));
        kullaniciaditext.setText("Kullanıcı Adı:");
        jPanel1.add(kullaniciaditext, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 80, 20));

        arkaplan.setBackground(new java.awt.Color(51, 153, 0));
        arkaplan.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\giris.png")); // NOI18N
        arkaplan.setOpaque(false);
        jPanel1.add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciadiActionPerformed
        // TODO add your handling code here:
        //kullanıcı adı
    }//GEN-LAST:event_kullaniciadiActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        //şifre
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dogruKullaniciAdi = "furkan";
        String dogruSifre = "furkan";

        String girilenKullaniciAdi = kullaniciadi.getText();
        String girilenSifre = new String(jPasswordField1.getPassword());

        boolean kullaniciAdiDogru = girilenKullaniciAdi.equals(dogruKullaniciAdi);
        boolean sifreDogru = girilenSifre.equals(dogruSifre);

        if (!kullaniciAdiDogru && !sifreDogru) {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı ve şifre yanlış", "Hata", JOptionPane.ERROR_MESSAGE);
        } else if (!kullaniciAdiDogru) {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı yanlış", "Hata", JOptionPane.ERROR_MESSAGE);
        } else if (!sifreDogru) {
            JOptionPane.showMessageDialog(this, "Şifre yanlış", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            AnaSayfa as = new AnaSayfa();
            as.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField kullaniciadi;
    private javax.swing.JLabel kullaniciaditext;
    private javax.swing.JLabel password;
    private javax.swing.JLabel saglıkmerkezi;
    // End of variables declaration//GEN-END:variables
}
