/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessproje;

/**
 *
 * @author TozLu
 */
public class kas extends javax.swing.JFrame {

    /**
     * Creates new form kiloverkasyap1
     */
    public kas() {
        initComponents();
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        KARINEGZERSİZ = new javax.swing.JLabel();
        rusbükümü = new javax.swing.JLabel();
        bacakkaldırma = new javax.swing.JLabel();
        topugadokunma = new javax.swing.JLabel();
        karıncrunch = new javax.swing.JLabel();
        GÖGÜSEGZERSİZ = new javax.swing.JLabel();
        gögüsgerme = new javax.swing.JLabel();
        dizdensinav = new javax.swing.JLabel();
        geniskolsinavi = new javax.swing.JLabel();
        inclinesinav = new javax.swing.JLabel();
        OMUZKOLEGZERSİZ = new javax.swing.JLabel();
        ücbaslıkas = new javax.swing.JLabel();
        kolkaldırma = new javax.swing.JLabel();
        karosinav = new javax.swing.JLabel();
        atlamakrikolari = new javax.swing.JLabel();
        proteindegerlerihandclick = new javax.swing.JLabel();
        kasyapmakhandclick = new javax.swing.JLabel();
        kilovermekhandclick = new javax.swing.JLabel();
        saglıktavsiyelerihandclick = new javax.swing.JLabel();
        anasayfaHandClick = new javax.swing.JLabel();
        arkapanel = new javax.swing.JLabel();
        anasayfa = new javax.swing.JButton();
        tavsiye = new javax.swing.JButton();
        kilover = new javax.swing.JButton();
        protein = new javax.swing.JButton();
        anasayfa1 = new javax.swing.JButton();
        kasyapmak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1920, 1920));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1920));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1920));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KARINEGZERSİZ.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        KARINEGZERSİZ.setForeground(new java.awt.Color(255, 255, 255));
        KARINEGZERSİZ.setText("KARIN EGZERSİZLERİ");
        jPanel1.add(KARINEGZERSİZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 430, 40));

        rusbükümü.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\rusbükümü.png")); // NOI18N
        jPanel1.add(rusbükümü, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 250, 300));

        bacakkaldırma.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\bacakkaldırma.png")); // NOI18N
        jPanel1.add(bacakkaldırma, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 250, 300));

        topugadokunma.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\topugadokunma.png")); // NOI18N
        jPanel1.add(topugadokunma, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 300, 250, 300));

        karıncrunch.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\karın.png")); // NOI18N
        jPanel1.add(karıncrunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 300, 250, 300));

        GÖGÜSEGZERSİZ.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        GÖGÜSEGZERSİZ.setForeground(new java.awt.Color(255, 255, 255));
        GÖGÜSEGZERSİZ.setText("GÖĞÜS EGZERSİZLERİ");
        jPanel1.add(GÖGÜSEGZERSİZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, 430, 40));

        gögüsgerme.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\gögüsgerme.png")); // NOI18N
        jPanel1.add(gögüsgerme, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 770, 250, 300));

        dizdensinav.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\dizdensinav.png")); // NOI18N
        jPanel1.add(dizdensinav, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 770, 250, 300));

        geniskolsinavi.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\genis.png")); // NOI18N
        jPanel1.add(geniskolsinavi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 770, 250, 300));

        inclinesinav.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\inclinesinav.png")); // NOI18N
        jPanel1.add(inclinesinav, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 770, 250, 300));

        OMUZKOLEGZERSİZ.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        OMUZKOLEGZERSİZ.setForeground(new java.awt.Color(255, 255, 255));
        OMUZKOLEGZERSİZ.setText("Omuz & Kol Egzersizleri");
        jPanel1.add(OMUZKOLEGZERSİZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1190, 470, 40));

        ücbaslıkas.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\ücbaslidips.png")); // NOI18N
        jPanel1.add(ücbaslıkas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1250, 250, 300));

        kolkaldırma.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\kolkaldırma.png")); // NOI18N
        jPanel1.add(kolkaldırma, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1240, 250, 300));

        karosinav.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\karosinav.png")); // NOI18N
        jPanel1.add(karosinav, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 1240, 250, 300));

        atlamakrikolari.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\atlamakrikolari.png")); // NOI18N
        jPanel1.add(atlamakrikolari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 1240, 250, 300));

        proteindegerlerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(proteindegerlerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 260, 110));

        kasyapmakhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kasyapmakhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 50, 290, 140));

        kilovermekhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kilovermekhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, 200, 110));

        saglıktavsiyelerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(saglıktavsiyelerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 170));

        anasayfaHandClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(anasayfaHandClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 140, 130));

        arkapanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\kasyapmak.png")); // NOI18N
        jPanel1.add(arkapanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 2530, 1960));

        anasayfa.setText("jButton1");
        anasayfa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anasayfa.setOpaque(false);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 120, 100));

        tavsiye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tavsiye.setOpaque(false);
        tavsiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavsiyeActionPerformed(evt);
            }
        });
        jPanel1.add(tavsiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 150));

        kilover.setText("jButton4");
        kilover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilover.setOpaque(false);
        kilover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiloverActionPerformed(evt);
            }
        });
        jPanel1.add(kilover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 190, 140));

        protein.setText("jButton2");
        protein.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        protein.setOpaque(false);
        protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinActionPerformed(evt);
            }
        });
        jPanel1.add(protein, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, 100));

        anasayfa1.setText("jButton4");
        anasayfa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anasayfa1.setOpaque(false);
        anasayfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfa1ActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 120, 110));

        kasyapmak.setText("jButton1");
        kasyapmak.setOpaque(false);
        kasyapmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasyapmakActionPerformed(evt);
            }
        });
        jPanel1.add(kasyapmak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 40, 340, 160));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        // TODO add your handling code here:
        AnaSayfa as= new AnaSayfa();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void tavsiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tavsiyeActionPerformed

        tavsiye1 t= new tavsiye1();
        t.setVisible(true);
        dispose();

    }//GEN-LAST:event_tavsiyeActionPerformed

    private void kiloverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiloverActionPerformed
        // TODO add your handling code here:
        kilovermek kilover = new kilovermek();
        kilover.setVisible(true);
        dispose();
    }//GEN-LAST:event_kiloverActionPerformed

    private void proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinActionPerformed
        // TODO add your handling code here:
        protein p= new protein();
        p.setVisible(true);

        dispose();
    }//GEN-LAST:event_proteinActionPerformed

    private void anasayfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anasayfa1ActionPerformed

    private void kasyapmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasyapmakActionPerformed

    }//GEN-LAST:event_kasyapmakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GÖGÜSEGZERSİZ;
    private javax.swing.JLabel KARINEGZERSİZ;
    private javax.swing.JLabel OMUZKOLEGZERSİZ;
    private javax.swing.JButton anasayfa;
    private javax.swing.JButton anasayfa1;
    private javax.swing.JLabel anasayfaHandClick;
    private javax.swing.JLabel arkapanel;
    private javax.swing.JLabel atlamakrikolari;
    private javax.swing.JLabel bacakkaldırma;
    private javax.swing.JLabel dizdensinav;
    private javax.swing.JLabel geniskolsinavi;
    private javax.swing.JLabel gögüsgerme;
    private javax.swing.JLabel inclinesinav;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel karosinav;
    private javax.swing.JLabel karıncrunch;
    private javax.swing.JButton kasyapmak;
    private javax.swing.JLabel kasyapmakhandclick;
    private javax.swing.JButton kilover;
    private javax.swing.JLabel kilovermekhandclick;
    private javax.swing.JLabel kolkaldırma;
    private javax.swing.JButton protein;
    private javax.swing.JLabel proteindegerlerihandclick;
    private javax.swing.JLabel rusbükümü;
    private javax.swing.JLabel saglıktavsiyelerihandclick;
    private javax.swing.JButton tavsiye;
    private javax.swing.JLabel topugadokunma;
    private javax.swing.JLabel ücbaslıkas;
    // End of variables declaration//GEN-END:variables
}
