/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessproje;

/**
 *
 * @author TozLu
 */
public class kilovermek extends javax.swing.JFrame {

    /**
     * Creates new form kilovermek
     */
    public kilovermek() {
        initComponents();
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        sudiyet = new javax.swing.JLabel();
        orucdiyeti1 = new javax.swing.JLabel();
        paleodiyeti1 = new javax.swing.JLabel();
        vegandiyeti = new javax.swing.JLabel();
        ketojenikdiyet = new javax.swing.JLabel();
        flexitariandiyet = new javax.swing.JLabel();
        sudiyeti = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aralıklıoruc = new javax.swing.JLabel();
        paleodiyet = new javax.swing.JLabel();
        akdenizdiyeti = new javax.swing.JLabel();
        vegandiyet = new javax.swing.JLabel();
        ketodiyet = new javax.swing.JLabel();
        flexitariandiyeti = new javax.swing.JLabel();
        kasyapmahandclick = new javax.swing.JLabel();
        anasayfaHandClick = new javax.swing.JLabel();
        saglıktavsiyelerihandclick = new javax.swing.JLabel();
        proteindegerlerihandclick = new javax.swing.JLabel();
        kilovermekhandclick = new javax.swing.JLabel();
        kasyapmakhandclick = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();
        tavsiye = new javax.swing.JButton();
        kilover = new javax.swing.JButton();
        protein = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        kasyap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1920));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sudiyet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sudiyet.setForeground(new java.awt.Color(255, 255, 255));
        sudiyet.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p>\nGünümüzde adından sıklıkla bahsedilen su diyeti yaşamın devamlılığı için elzem olan suyu merkezine alan bir diyet biçimidir. <br> Belirli dönemlerde yapılan diyetler kilo vermeye olduğu kadar sağlığı korumaya da yardımcı olabilir. <br> Su diyeti 24-72 saat boyunca su başta olmak üzere sadece sıvı gıdaların tüketildiği bir diyet şeklidir.\n</p> </html>");
        sudiyet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(sudiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1710, 1210, 120));

        orucdiyeti1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orucdiyeti1.setForeground(new java.awt.Color(255, 255, 255));
        orucdiyeti1.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p>Aralıklı oruç, günü ikiye bölen, 16 saat aç kalıp kalan 8 saatte yemek yenilmesini içeren, özetle 24 saat içerisinde hem kahvaltı <br>  hem de akşam yemeği olmak üzere 2 öğünden oluşan beslenme şeklidir. 16:8 kuralı olarak bilinen 16 saat yemek  <br>yenmemesi sonrası kalan 8 saatte sağlıklı bir şekilde beslenilmesini savunur. Aralıklı oruçtaki bu 16 saatlik açlığın içine  <br>uyku saatleri de dahildir.</p> </html>");
        jPanel1.add(orucdiyeti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 130));

        paleodiyeti1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paleodiyeti1.setForeground(new java.awt.Color(255, 255, 255));
        paleodiyeti1.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p>\nPaleo diyeti, protein ağırlıklı bir diyet olup, işlenmemiş ve doğal gıdalardan oluşur ve zayıflatmaya yardımcıdır. <br>\nKarbonhidrat, rafine şekerler, yapay tatlandırıcılar, katkı maddeleri, koruyucu maddeler ve işlenmiş gıdalardan kaçınır.<br>\nPaleo diyeti, et ürünleri ağırlıklı olmak üzere doğal ürünlere öncelik veren beslenme çeşididir, en sağlıklı diyetler arasında yer almaktadır.\n</p> </html>");
        paleodiyeti1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(paleodiyeti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 1190, 120));

        vegandiyeti.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vegandiyeti.setForeground(new java.awt.Color(255, 255, 255));
        vegandiyeti.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p> Akdeniz diyeti, Akdeniz havzası çevresinde gelişen eski uygarlıkların yemek kültürlerinden ismini almıştır. Bir beslenme modelidir. \n<br>Yağ alımının ana kaynağı olarak zeytinyağı düzenli olarak tüketilir.\n Akdeniz diyeti; bitkisel gıdalar, tahıllar, meyveler, sebzeler, baklagiller ve yağlı tohumlar tüketimine dayanır. \nKırmızı et ve diğer et ürünlerinin nispeten sınırlı tüketimini dengelemeyi amaçlarken; orta düzeyde balık, deniz ürünleri ve süt ürünleri tüketilir </p> </html>");
        vegandiyeti.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(vegandiyeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 760, 1210, 120));

        ketojenikdiyet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ketojenikdiyet.setForeground(new java.awt.Color(255, 255, 255));
        ketojenikdiyet.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p>Vegan diyeti, yalnızca bitkisel ürünler kullanılarak yapılmaktadır. <br>Böylelikle yumurta, süt ve süt ürünleri, bal, et, balık, tavuk, yoğurt, peynir gibi hiçbir gıda tüketimi yapılmamaktadır. <br>Bunun yanı sıra badem sütü, hindistancevizi sütü ve soyu sütü gibi tamamen bitkisel süt çeşitleri tüketilebilmektedir. </p> </html>");
        ketojenikdiyet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(ketojenikdiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 990, 1210, 120));

        flexitariandiyet.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        flexitariandiyet.setForeground(new java.awt.Color(255, 255, 255));
        flexitariandiyet.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p>\nKilo vermeyi destekleyen ketojenik diyet, <br>kan şekerini düzenler, enerji seviyesini artırır ve bunların yanında sağlık için birçok fayda sağlar.\n<br>Fakat bu diyetin uzun süreler uygulanması riskli olabilmektedir. <br>\nBu yüzden uzman doktordan görüş alarak bu diyeti sürdürmek ve ilerlemek önemlidir.<br>\n</p> </html>");
        flexitariandiyet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(flexitariandiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1230, 1210, 120));

        sudiyeti.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sudiyeti.setForeground(new java.awt.Color(255, 255, 255));
        sudiyeti.setText("<html>  <style>  p{  color: white ; font-size: 16px; line-height: 1.6px;   }   </style>  <p>\nFlexitarian diyet, vegan diyetin daha esnek hali olarak sayılabilir. <br> Peskateryan diyetlerde vegan ürünlerine ek olarak balık, et, süt ürünleride tüketilebilir<br> ama bunu en az da tutmaya çalışır ve esnek bir diyeti bize sunar<br>Sağlıklı kilo verme konusunda en çok tercih edilen 3 diyetten biridir.\n</p> </html>");
        sudiyeti.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(sudiyeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1470, 1210, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SU DİYETİ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1660, 180, 40));

        aralıklıoruc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aralıklıoruc.setForeground(new java.awt.Color(255, 255, 255));
        aralıklıoruc.setText("ARALIKLI ORUÇ");
        jPanel1.add(aralıklıoruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 170, 40));

        paleodiyet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paleodiyet.setForeground(new java.awt.Color(255, 255, 255));
        paleodiyet.setText("PALEO DİYETİ");
        jPanel1.add(paleodiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 170, 40));

        akdenizdiyeti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        akdenizdiyeti.setForeground(new java.awt.Color(255, 255, 255));
        akdenizdiyeti.setText("AKDENİZ DİYETİ");
        jPanel1.add(akdenizdiyeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 170, 40));

        vegandiyet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vegandiyet.setForeground(new java.awt.Color(255, 255, 255));
        vegandiyet.setText("VEGAN DİYETİ");
        jPanel1.add(vegandiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 950, 170, 40));

        ketodiyet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ketodiyet.setForeground(new java.awt.Color(255, 255, 255));
        ketodiyet.setText("KETOJENİK DİYETİ");
        jPanel1.add(ketodiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1190, 170, 40));

        flexitariandiyeti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        flexitariandiyeti.setForeground(new java.awt.Color(255, 255, 255));
        flexitariandiyeti.setText("FLEXİTARİAN DİYETİ");
        jPanel1.add(flexitariandiyeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1430, 180, 40));

        kasyapmahandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kasyapmahandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 40, 300, 150));

        anasayfaHandClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(anasayfaHandClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 160, 130));
        jPanel1.add(saglıktavsiyelerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 170));

        proteindegerlerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(proteindegerlerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 260, 110));

        kilovermekhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kilovermekhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, 200, 110));

        kasyapmakhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kasyapmakhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 50, 290, 140));

        arkaplan.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\diyet menü.png")); // NOI18N
        jPanel1.add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tavsiye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tavsiye.setOpaque(false);
        tavsiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavsiyeActionPerformed(evt);
            }
        });
        jPanel1.add(tavsiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 150));

        kilover.setText("jButton4");
        kilover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilover.setOpaque(false);
        kilover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiloverActionPerformed(evt);
            }
        });
        jPanel1.add(kilover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 200, 140));

        protein.setText("jButton2");
        protein.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        protein.setOpaque(false);
        protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinActionPerformed(evt);
            }
        });
        jPanel1.add(protein, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, 100));

        anasayfa.setText("jButton4");
        anasayfa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anasayfa.setOpaque(false);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 140, 110));

        kasyap.setText("jButton1");
        kasyap.setOpaque(false);
        kasyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasyapActionPerformed(evt);
            }
        });
        jPanel1.add(kasyap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 40, 340, 160));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tavsiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tavsiyeActionPerformed

        tavsiye1 t= new tavsiye1();
        t.setVisible(true);
        dispose();

    }//GEN-LAST:event_tavsiyeActionPerformed

    private void proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinActionPerformed
        // TODO add your handling code here:
        protein p= new protein();
        p.setVisible(true);

        dispose();
    }//GEN-LAST:event_proteinActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        AnaSayfa as= new AnaSayfa();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void kasyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasyapActionPerformed
        kas kk= new kas();
        kk.setVisible(true);
        dispose();
    }//GEN-LAST:event_kasyapActionPerformed

    private void kiloverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiloverActionPerformed

    }//GEN-LAST:event_kiloverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kilovermek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kilovermek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kilovermek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kilovermek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kilovermek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akdenizdiyeti;
    private javax.swing.JButton anasayfa;
    private javax.swing.JLabel anasayfaHandClick;
    private javax.swing.JLabel aralıklıoruc;
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel flexitariandiyet;
    private javax.swing.JLabel flexitariandiyeti;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kasyap;
    private javax.swing.JLabel kasyapmahandclick;
    private javax.swing.JLabel kasyapmakhandclick;
    private javax.swing.JLabel ketodiyet;
    private javax.swing.JLabel ketojenikdiyet;
    private javax.swing.JButton kilover;
    private javax.swing.JLabel kilovermekhandclick;
    private javax.swing.JLabel orucdiyeti1;
    private javax.swing.JLabel paleodiyet;
    private javax.swing.JLabel paleodiyeti1;
    private javax.swing.JButton protein;
    private javax.swing.JLabel proteindegerlerihandclick;
    private javax.swing.JLabel saglıktavsiyelerihandclick;
    private javax.swing.JLabel sudiyet;
    private javax.swing.JLabel sudiyeti;
    private javax.swing.JButton tavsiye;
    private javax.swing.JLabel vegandiyet;
    private javax.swing.JLabel vegandiyeti;
    // End of variables declaration//GEN-END:variables
}
