/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessproje;

/**
 *
 * @author TozLu
 */
public class protein extends javax.swing.JFrame {

    /**
     * Creates new form protein
     */
    public protein() {
        initComponents();
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        anasayfaHandClick1 = new javax.swing.JLabel();
        süt = new javax.swing.JLabel();
        yumurta = new javax.swing.JLabel();
        tavuketi = new javax.swing.JLabel();
        yulaf = new javax.swing.JLabel();
        bezelye = new javax.swing.JLabel();
        danaeti = new javax.swing.JLabel();
        kasyapmakhandclick = new javax.swing.JLabel();
        kilovermekhandclick = new javax.swing.JLabel();
        anasayfaHandClick = new javax.swing.JLabel();
        proteindegerlerihandclick = new javax.swing.JLabel();
        saglıktavsiyelerihandclick = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();
        tavsiye = new javax.swing.JButton();
        kilover = new javax.swing.JButton();
        protein = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        kasyapmak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1920, 1920));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anasayfaHandClick1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(anasayfaHandClick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 120, 100));

        süt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        süt.setForeground(new java.awt.Color(153, 255, 255));
        süt.setText("<html>\nKestiğimizde etiyle, sağdığımızda sütüyle bize yarar sağlayan, gübresiyle bile besin yetiştirebildiğimiz bu mucizevi canlının sütünden çıkan besin değerine hadi beraber bakalım.\nYaklaşık 100 gram inek sütünde 3.3 gram protein, 3.8 gram yağ, 4.7 gram karbonhidrat, 3.3 gram laktoz(süt şekeri) bulunur ve laktoza alerjisi olanların kesinlikle dikkat etmesi gerekir. \n</html>");
        jPanel1.add(süt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1620, 1110, 140));

        yumurta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        yumurta.setForeground(new java.awt.Color(51, 255, 0));
        yumurta.setText("<html>  Sporcuların 1.numaralı dostu olan yumurtayı sizin için 1.sıraya aldık hem ekonomik hemde besin değeri açısından zengin bu besinin besin değerini inceleyelim.  100 gram(2 adet) yumurtanın içinde 12,58 gram protein bulunurken 10,61 gram yağ ve 1.12 gram karbonhidrat içerir, 165 kalori içerir.  Yumurtanın pişme durumuna göre değişir bu durum. 100 gram çiğ yumurtanın  içinde 12,9 gram protein, 0,7 gram karbonhidrat, 11,2 gram yağ içerir.  </html>");
        jPanel1.add(yumurta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 1230, 150));

        tavuketi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tavuketi.setForeground(new java.awt.Color(153, 255, 255));
        tavuketi.setText("<html>  Tavuk göğsü tavuğun diğer yapılarına göre biraz daha tatsız olsada besin değeri olarak hiç aşağı kalır yanı yoktur. \n100 gram tavuk göğsünün içinde 22.5 gram protein, 2.6 gram yağ, 0 gram karbonhidrat ve 120 kalori bulunur. \nBu bilgilere ek olarak, 73mg kolesterol, 30.0 IU A VİTAMİNİ, 334mg potasyum, 5 mg Kalsiyum ve 0.4 mg Demir içerir.   \n</html>");
        jPanel1.add(tavuketi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 1050, 140));

        yulaf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        yulaf.setForeground(new java.awt.Color(153, 255, 255));
        yulaf.setText("<html> \nEkonomik ve doyurucu olmasından ötürü sporcularca çokça tercih edilen yulaf aynı zamanda onlar içinde yemesi eziyet olan besindir tatsız ve saman yiyor hissiyatı yaratsada malesef ki vazgeçilemiyor, hadi gelin bu eziyet verici besinin besin değerine bakalım. 100 gram yulafta, 57.25 gram karbonhidrat, 11.35 gram protein, 5.8 gram yağ, 12.24 gram lif bulunur. Gelde kullanma bu mucizeyi!  \n</html>");
        jPanel1.add(yulaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 870, 1110, 140));

        bezelye.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bezelye.setForeground(new java.awt.Color(153, 255, 255));
        bezelye.setText("<html>\nHerkes tarafından çok bilinmeyen ama bir sebzeye göre gayet iyi bir protein değerine sahip olan bezelye 100 gramında,\n 5gram protein, 14 gram karbonhidrat, 0.4 gram yağ içerir 81 kaloridir. \nİçindeki diğer ögeler: C vitamini, Demir, B6, Magnezyum, Kalsiyum, D vitamini, Kobalamin, Potasyum, Sodyum. Muazzam bir besin!\n</html>");
        jPanel1.add(bezelye, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1120, 1110, 140));

        danaeti.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        danaeti.setForeground(new java.awt.Color(153, 255, 255));
        danaeti.setText("<html>\nOrta direk için artık bir rüya haline gelmeye başlayan dana etinide listeye almaya karar verdik, gelin beraber dana etinin besin değerine beraber bakalım.\n100 gramında, 20 gram protein, 8 gram yağ ve 0 gram karbonhidrat bulundurur. Yağlısı 18 gram protein, 16 gram yağ içerir. Az yağlısı 150 kalori iken yağlısı 220 grama denk düşmektedir.\n</html>");
        jPanel1.add(danaeti, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1370, 1110, 140));

        kasyapmakhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kasyapmakhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 50, 290, 140));

        kilovermekhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kilovermekhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, 200, 110));

        anasayfaHandClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(anasayfaHandClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 140, 130));

        proteindegerlerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(proteindegerlerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 260, 110));

        saglıktavsiyelerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(saglıktavsiyelerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 170));

        arkaplan.setForeground(new java.awt.Color(255, 0, 51));
        arkaplan.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\proteindegerleri.png")); // NOI18N
        jPanel1.add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tavsiye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tavsiye.setOpaque(false);
        tavsiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavsiyeActionPerformed(evt);
            }
        });
        jPanel1.add(tavsiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 150));

        kilover.setText("jButton4");
        kilover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilover.setOpaque(false);
        kilover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiloverActionPerformed(evt);
            }
        });
        jPanel1.add(kilover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 190, 140));

        protein.setText("jButton2");
        protein.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        protein.setOpaque(false);
        protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinActionPerformed(evt);
            }
        });
        jPanel1.add(protein, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, 100));

        anasayfa.setText("jButton4");
        anasayfa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anasayfa.setOpaque(false);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 120, 110));

        kasyapmak.setText("jButton1");
        kasyapmak.setOpaque(false);
        kasyapmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasyapmakActionPerformed(evt);
            }
        });
        jPanel1.add(kasyapmak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 40, 340, 160));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tavsiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tavsiyeActionPerformed

        tavsiye1 t= new tavsiye1();
        t.setVisible(true);
        dispose();

    }//GEN-LAST:event_tavsiyeActionPerformed

    private void kiloverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiloverActionPerformed
        // TODO add your handling code here:
        kilovermek kilover = new kilovermek();
        kilover.setVisible(true);
        dispose();
    }//GEN-LAST:event_kiloverActionPerformed

    private void proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinActionPerformed

    }//GEN-LAST:event_proteinActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        AnaSayfa as= new AnaSayfa();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void kasyapmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasyapmakActionPerformed
        kas kk= new kas();
        kk.setVisible(true);
        dispose();
    }//GEN-LAST:event_kasyapmakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(protein.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(protein.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(protein.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(protein.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new protein().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JLabel anasayfaHandClick;
    private javax.swing.JLabel anasayfaHandClick1;
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel bezelye;
    private javax.swing.JLabel danaeti;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kasyapmak;
    private javax.swing.JLabel kasyapmakhandclick;
    private javax.swing.JButton kilover;
    private javax.swing.JLabel kilovermekhandclick;
    private javax.swing.JButton protein;
    private javax.swing.JLabel proteindegerlerihandclick;
    private javax.swing.JLabel saglıktavsiyelerihandclick;
    private javax.swing.JLabel süt;
    private javax.swing.JButton tavsiye;
    private javax.swing.JLabel tavuketi;
    private javax.swing.JLabel yulaf;
    private javax.swing.JLabel yumurta;
    // End of variables declaration//GEN-END:variables
}
