/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessproje;

/**
 *
 * @author TozLu
 */
public class supplement extends javax.swing.JFrame {

    /**
     * Creates new form supplement
     */
    public supplement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gainer = new javax.swing.JLabel();
        bcaa = new javax.swing.JLabel();
        proteintozu = new javax.swing.JLabel();
        carnitine = new javax.swing.JLabel();
        preworkout = new javax.swing.JLabel();
        kreatin = new javax.swing.JLabel();
        anasayfaHandClick = new javax.swing.JLabel();
        saglıktavsiyelerihandclick = new javax.swing.JLabel();
        proteindegerlerihandclick = new javax.swing.JLabel();
        kilovermekhandclick = new javax.swing.JLabel();
        kasyapmakhandclick = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();
        tavsiye = new javax.swing.JButton();
        kilover = new javax.swing.JButton();
        protein = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        kasyapmak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gainer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gainer.setText("<html>\nGainer kilo almak isteyen insanların 1.numaralı tercihi olmakla beraber uygun fiyatı ile de herkesin alabileceği bir ürün haline geliyor, işte Gainerin yararları ve zararları: Kilo alımını ve kas kütlesi artışını destekleyebilir, antrenman performansını artırabilir, ancak yan etkiler arasında sindirim sorunları, kilo alımı ve yağ birikimi bulunabilir; bu nedenle kullanmadan önce bir sağlık uzmanına danışmak önemlidir.\n</html>");
        jPanel1.add(gainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 660, 730, 100));

        bcaa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bcaa.setText("<html> Yapılan araştırmalar BCAA'nın onarıcı özelliği ve kas yorgunluğunu minimuma indirdiğini göstermektedir.\n Lösin, izolösin, valine gibi vücutta üretilemeyen aminoasitleri barındırdığından ötürü kesinlikle 1.numaralı supplementler arasında gösterilir.\n Şimdi bide yan etkilerine gelelim: Zaman içerisinde zihnin dinlenmesini önüne geçer ve baş dönmesi, baş ağrısı gibi semptomlar gösterir. ! </html>");
        jPanel1.add(bcaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 730, 90));

        proteintozu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        proteintozu.setText("<html> Protein tozu, her spora başlayanın 1.numaralı supplementidir? Peki yararları ve yan etkileri nelermiş beraber görelim! \nKas protein sentezini tetikleyerek kas miktarının artmasına ve güçlenmesine katkıda bulunur. \nProtein tozu, antrenman sonrası kas ağrılarını azaltır ve iyileşme sürecini hızlandırır.\nSıra yan etkilerinde: Böbrek fonksiyonlarının olumsuz etkilenmesi, karaciğer fonksiyon bozukluğu yaşanması, gaz, şişkinlik, ishal ve gut hastalığı gibi sonuçları olabilir. Ölçülü kullan!</html>");
        jPanel1.add(proteintozu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 730, 100));

        carnitine.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        carnitine.setText("<html> \nVücudun enerji üretim sürecinde önemli rol oynayan l-karnitinin yararlı yanlarını ve yan etkilerini sizin için sayıyoruz.\n L-karnitin, yağların yakımını hızlandırarak enerji üretimini arttırır, Ezgersiz performansını arttırır, Kas kütlesini destekler, kalp sağlığını riskini azaltan araştırmalar öne sürülmüştür. \nŞimdi gelelim yan etkilerine! Yüksek dozda alındığında kalp hastalığında mide rahatsızlığına sebep olabilir, \nTer kokusunu olumsuz etkileyebilir, yüksek dozda alındığında uykusuzluğa yol açabilir, nadir durumlarda alerjik olabilir.\n!</html>");
        jPanel1.add(carnitine, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 730, 100));

        preworkout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        preworkout.setText("<html> Antrenman sırasında insanlara yüksek seviye enerji veren ve antrenmanın daha güzel hale gelmesine sebep olan Pre-workout takviyeleri nin yararları ve yan etkileri, antrenman performansını artırabilir, dayanıklılığı destekleyebilir, odaklanmayı artırabilir ve kasları daha hızlı toparlanmaya teşvik edebilirken, yan etkiler arasında uykusuzluk, sinirlilik, mide rahatsızlıkları ve kalp atışlarında artış bulunabilir.\n!</html>");
        jPanel1.add(preworkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 290, 730, 100));

        kreatin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kreatin.setText("<html>\nAntrenmanda kasların gördüğü hasarı daha hızlı onarmasıyla ve kas gelişimine katkısı bilimsel olarak ispatlanmış creatinin yararları ve zararları: \ngüç ve dayanıklılığı artırabilir, kas kütlesini ve egzersiz performansını artırabilir, ancak yan etkiler arasında sindirim sorunları, su tutma, kas krampları ve böbrek stresi bulunabilir.\n</html>");
        jPanel1.add(kreatin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 480, 730, 100));

        anasayfaHandClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(anasayfaHandClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 140, 130));

        saglıktavsiyelerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(saglıktavsiyelerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 170));

        proteindegerlerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(proteindegerlerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 260, 110));

        kilovermekhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kilovermekhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, 200, 110));

        kasyapmakhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kasyapmakhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 50, 290, 140));

        arkaplan.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\supplement.png")); // NOI18N
        jPanel1.add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 1960, -1));

        tavsiye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tavsiye.setOpaque(false);
        tavsiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavsiyeActionPerformed(evt);
            }
        });
        jPanel1.add(tavsiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 150));

        kilover.setText("jButton4");
        kilover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilover.setOpaque(false);
        kilover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiloverActionPerformed(evt);
            }
        });
        jPanel1.add(kilover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 190, 140));

        protein.setText("jButton2");
        protein.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        protein.setOpaque(false);
        protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinActionPerformed(evt);
            }
        });
        jPanel1.add(protein, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, 100));

        anasayfa.setText("jButton4");
        anasayfa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anasayfa.setOpaque(false);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 120, 110));

        kasyapmak.setText("jButton1");
        kasyapmak.setOpaque(false);
        kasyapmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasyapmakActionPerformed(evt);
            }
        });
        jPanel1.add(kasyapmak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 40, 340, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tavsiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tavsiyeActionPerformed

        tavsiye1 t= new tavsiye1();
        t.setVisible(true);
        dispose();

    }//GEN-LAST:event_tavsiyeActionPerformed

    private void kiloverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiloverActionPerformed
        // TODO add your handling code here:
        kilovermek kilover = new kilovermek();
        kilover.setVisible(true);
        dispose();
    }//GEN-LAST:event_kiloverActionPerformed

    private void proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinActionPerformed
        // TODO add your handling code here:
        protein p= new protein();
        p.setVisible(true);

        dispose();
    }//GEN-LAST:event_proteinActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        AnaSayfa as= new AnaSayfa();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void kasyapmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasyapmakActionPerformed
        kas kk= new kas();
        kk.setVisible(true);
        dispose();
    }//GEN-LAST:event_kasyapmakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JLabel anasayfaHandClick;
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel bcaa;
    private javax.swing.JLabel carnitine;
    private javax.swing.JLabel gainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kasyapmak;
    private javax.swing.JLabel kasyapmakhandclick;
    private javax.swing.JButton kilover;
    private javax.swing.JLabel kilovermekhandclick;
    private javax.swing.JLabel kreatin;
    private javax.swing.JLabel preworkout;
    private javax.swing.JButton protein;
    private javax.swing.JLabel proteindegerlerihandclick;
    private javax.swing.JLabel proteintozu;
    private javax.swing.JLabel saglıktavsiyelerihandclick;
    private javax.swing.JButton tavsiye;
    // End of variables declaration//GEN-END:variables
}
