/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitnessproje;

/**
 *
 * @author TozLu
 */
public class tavsiye1 extends javax.swing.JFrame {

    /**
     * Creates new form tavsiye1
     */
    public tavsiye1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        supplementtext = new javax.swing.JLabel();
        hazırgıdatext = new javax.swing.JLabel();
        steroidtext = new javax.swing.JLabel();
        kafeintext = new javax.swing.JLabel();
        sebzetext = new javax.swing.JLabel();
        ettext = new javax.swing.JLabel();
        anasayfaHandClick = new javax.swing.JLabel();
        saglıktavsiyelerihandclick = new javax.swing.JLabel();
        proteindegerlerihandclick = new javax.swing.JLabel();
        kilovermekhandclick = new javax.swing.JLabel();
        kasyapmakhandclick = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();
        supplementayrıntı = new javax.swing.JButton();
        tavsiye = new javax.swing.JButton();
        kilover = new javax.swing.JButton();
        protein = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        kasyapmak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplementtext.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        supplementtext.setText("<html> Yıllardır hayatımızda olan ve bize ucuza; enerji, protein, kilo, kas gücü sağlayan supplementler bize çok masum görünürken bilinmeyen yan etkileriniden bilmekte yarar vardır. Size kısaca bazı supplementlerin yan etkilerini sayacaz. HADİ HAZIRSANIZ BAŞLAYALIM! </html>");
        supplementtext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(supplementtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 730, 90));

        hazırgıdatext.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        hazırgıdatext.setText("<html>\nHazır gıdaların yüksek şeker, yağ ve tuz içeriği, sporcular için gereken besin ögelerini yetersiz sağlayabilir ve kilo kontrolünü zorlaştırabilir. Ayrıca, katkı maddeleri ve düşük kaliteli proteinlerin uzun vadede sağlık sorunlarına yol açabileceği bilinmektedir. Bu nedenle, dengeli bir beslenme planı oluşturmak ve doğal, işlenmemiş gıdalara odaklanmak önemlidir.\n</html>");
        jPanel1.add(hazırgıdatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 670, 720, 90));

        steroidtext.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        steroidtext.setText("<html>\nKas üretim konusunda kısa vadede mükemmel sonuçlar almaya yarayan Steroidler, kas kütlesi artışı, performans iyileştirmesi ve iyileşme sürecini hızlandırma gibi olumlu etkilere sahip olabilirken, ciddi yan etkileri de bulunmaktadır.\n Bu yan etkiler arasında karaciğer hasarı, kalp problemleri, ruh hali değişiklikleri, hormonal dengesizlikler, akne, saç dökülmesi, erkeklerde meme büyümesi, kadınlarda sesin derinleşmesi gibi sağlık sorunları yer alır.\n Steroidlerin yan etkileri genellikle uzun süreli ve ciddidir, hatta bazen kalıcı hasara neden olabilirler.\n</html>");
        jPanel1.add(steroidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 730, 90));

        kafeintext.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        kafeintext.setText("<html>\nSporcuların ve gece çalışanlarının gözde ürünü olan Kafein, uyarıcı etkisiyle enerji seviyelerini artırabilir, odaklanmayı ve dikkati artırabilir, egzersiz performansını iyileştirebilir ve kısa vadeli zihinsel performansı artırabilir. Ancak, aşırı tüketildiğinde veya hassas bireylerde yan etkilere neden olabilir. Bunlar arasında uykusuzluk, sinirlilik, kalp çarpıntısı, mide rahatsızlığı ve bağımlılık yer alır. Uzun süreli yüksek düzeyde kafein tüketimi, uyku kalitesini bozabilir ve tolerans gelişimine yol açabilir. Bu nedenle, kafein alımını dengeli tutmak ve ölçülü tüketmek önemlidir.\n</html>");
        jPanel1.add(kafeintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 730, 90));

        sebzetext.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        sebzetext.setText("<html>\nSebzeler, fitness için önemlidir çünkü besleyici, düşük kalorili, sindirimi destekleyici, hidrasyon sağlayıcı ve performans artırıcıdır; ancak, \nbazıları için sindirim sorunlarına neden olabilir, bu nedenle çeşitli sebzeleri dengeli bir şekilde tüketmek önemlidir.\nSebzeler, göz sağlığından bağışıklık sistemine, kan pıhtılaşmasından hücre bölünmesine kadar birçok alanda önemli olan A, C, K ve B vitaminlerini içerir.\n</html>");
        jPanel1.add(sebzetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 290, 730, 90));

        ettext.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ettext.setText("<html>\nEt tüketmek, kas büyümesi ve onarımı için gerekli olan yüksek kaliteli protein ve önemli besin maddeleri sağlar; \nayrıca vücut kompozisyonunu iyileştirir, güç artışını destekler ve tokluk hissi verir.\nEt, demir, çinko, magnezyum gibi mineraller ile B12, B3 ve B2 gibi vitaminler açısından zengin bir kaynaktır.\n</html>");
        jPanel1.add(ettext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 480, 720, 90));

        anasayfaHandClick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(anasayfaHandClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 140, 130));

        saglıktavsiyelerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(saglıktavsiyelerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 170));

        proteindegerlerihandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(proteindegerlerihandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 260, 110));

        kilovermekhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kilovermekhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, 200, 110));

        kasyapmakhandclick.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(kasyapmakhandclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 50, 290, 140));

        arkaplan.setIcon(new javax.swing.ImageIcon("C:\\Users\\TozLu\\Documents\\NetBeansProjects\\fitnessproje\\src\\fitnessproje\\fxprojeresim\\sagliktavsiyeleri.png")); // NOI18N
        jPanel1.add(arkaplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 1960, -1));

        supplementayrıntı.setText("jButton1");
        supplementayrıntı.setOpaque(false);
        supplementayrıntı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplementayrıntıActionPerformed(evt);
            }
        });
        jPanel1.add(supplementayrıntı, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 900, 90));

        tavsiye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tavsiye.setOpaque(false);
        tavsiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tavsiyeActionPerformed(evt);
            }
        });
        jPanel1.add(tavsiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 340, 150));

        kilover.setText("jButton4");
        kilover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kilover.setOpaque(false);
        kilover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiloverActionPerformed(evt);
            }
        });
        jPanel1.add(kilover, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 190, 140));

        protein.setText("jButton2");
        protein.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        protein.setOpaque(false);
        protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinActionPerformed(evt);
            }
        });
        jPanel1.add(protein, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 250, 100));

        anasayfa.setText("jButton4");
        anasayfa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anasayfa.setOpaque(false);
        anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anasayfaActionPerformed(evt);
            }
        });
        jPanel1.add(anasayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 120, 110));

        kasyapmak.setText("jButton1");
        kasyapmak.setOpaque(false);
        kasyapmak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasyapmakActionPerformed(evt);
            }
        });
        jPanel1.add(kasyapmak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 40, 340, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tavsiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tavsiyeActionPerformed

        tavsiye1 t= new tavsiye1();
        t.setVisible(true);
        dispose();

    }//GEN-LAST:event_tavsiyeActionPerformed

    private void kiloverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiloverActionPerformed

        kilovermek kilover = new kilovermek();
        kilover.setVisible(true);
        dispose();
    }//GEN-LAST:event_kiloverActionPerformed

    private void proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinActionPerformed
        // TODO add your handling code here:
        protein p= new protein();
        p.setVisible(true);

        dispose();
    }//GEN-LAST:event_proteinActionPerformed

    private void anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anasayfaActionPerformed
        AnaSayfa as= new AnaSayfa();
        as.setVisible(true);
        dispose();
    }//GEN-LAST:event_anasayfaActionPerformed

    private void kasyapmakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasyapmakActionPerformed
        kas kk= new kas();
        kk.setVisible(true);
        dispose();
    }//GEN-LAST:event_kasyapmakActionPerformed

    private void supplementayrıntıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplementayrıntıActionPerformed
       supplement sa= new supplement();
       sa.setVisible(true);
        dispose();
    }//GEN-LAST:event_supplementayrıntıActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tavsiye1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tavsiye1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tavsiye1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tavsiye1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tavsiye1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anasayfa;
    private javax.swing.JLabel anasayfaHandClick;
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel ettext;
    private javax.swing.JLabel hazırgıdatext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kafeintext;
    private javax.swing.JButton kasyapmak;
    private javax.swing.JLabel kasyapmakhandclick;
    private javax.swing.JButton kilover;
    private javax.swing.JLabel kilovermekhandclick;
    private javax.swing.JButton protein;
    private javax.swing.JLabel proteindegerlerihandclick;
    private javax.swing.JLabel saglıktavsiyelerihandclick;
    private javax.swing.JLabel sebzetext;
    private javax.swing.JLabel steroidtext;
    private javax.swing.JButton supplementayrıntı;
    private javax.swing.JLabel supplementtext;
    private javax.swing.JButton tavsiye;
    // End of variables declaration//GEN-END:variables
}
